feat: add github user extractor
odpf/meteor pull request #134
Opened 2021-07-22 11:15 UTC by ravisuhag

This extractor pulls user data from github and creates a user metadata model.

2021-07-22 11:35 UTC, StewartJingga commented on core/extractor/extractor.go
> -		break
TIL break is implicit in go.👌

2021-07-22 11:40 UTC, StewartJingga commented
dont forget to list down your extractor [here](https://github.com/odpf/meteor/blob/main/docs/reference/extractors.md) as mentioned in [this guide](https://github.com/odpf/meteor/blob/main/docs/contribute/guide.md).

2021-07-22 11:42 UTC, StewartJingga requested changes
dont forget to list down your extractor [here](https://github.com/odpf/meteor/blob/main/docs/reference/extractors.md) as mentioned in [this guide](https://github.com/odpf/meteor/blob/main/docs/contribute/guide.md).

2021-07-22 12:01 UTC, ravisuhag commented
> dont forget to list down your extractor [here](https://github.com/odpf/meteor/blob/main/docs/reference/extractors.md) as mentioned in [this guide](https://github.com/odpf/meteor/blob/main/docs/contribute/guide.md).

Done!!!
@StewartJingga 
Also, how about tests for this? Actually, Not much to test apart from mocking the Github client. Any suggestion?

2021-07-23 07:45 UTC, StewartJingga commented
> > dont forget to list down your extractor [here](https://github.com/odpf/meteor/blob/main/docs/reference/extractors.md) as mentioned in [this guide](https://github.com/odpf/meteor/blob/main/docs/contribute/guide.md).
> 
> Done!!!
> @StewartJingga
> Also, how about tests for this? Actually, Not much to test apart from mocking the Github client. Any suggestion?

yeah been thinking about that as well, the best we could do is creating a mock and an interface of github client just to test if we are mapping the right data to meta.Table.

2021-07-23 23:56 UTC, merged