feat: improve error handling
odpf/meteor pull request #238
Opened 2021-09-27 19:21 UTC by scortier

2021-10-02 02:38 UTC, StewartJingga requested changes
Love the error wrapping but needs some changes on these two things:

1. Use `Wrap` instead of `Wrapf` if there is no string formatting.
2. For case where return value is already defined you can wrap error like below
```
if err != nil {
    err = errors.Wrap(err, "wrapping error")
    return
}
```

2021-10-02 02:38 UTC, StewartJingga commented on agent/stream.go
> +		s.err = errors.Wrapf(err, "emitter: error running middleware")
we use `Wrapf` if we want to format our error message.

2021-10-02 02:38 UTC, StewartJingga commented on generator/recipe.go
> +			return errors.Wrapf(err, "failed to provide extractor information")
same here, we use `Wrapf` if there is string formatting, we can use `Wrap` instead.

2021-10-02 02:38 UTC, StewartJingga commented on metrics/statsd.go
> +		return nil, errors.Wrapf(err, "failed to convert port type")
to handle this kind of code, it's better to do it like below
```
if err != nil {
        err = errors.Wrap(err, "failed to split a network address")
	return
}
```

2021-10-04 16:01 UTC, StewartJingga requested changes

2021-10-04 16:34 UTC, scortier commented on agent/agent.go
> +		run.Error = errors.Wrap(err, "failed to stream")
sounds good 👍

2021-10-05 02:25 UTC, StewartJingga approved these changes
LGTM

2021-10-05 02:25 UTC, merged